"""create ai processing runs and items

Creates the two service-owned tables backing report processing. Note
`uq_ai_run_items_active_report`: a PARTIAL unique index on report_id, restricted to
non-terminal statuses. It is the database-level idempotency guarantee -- at most one
in-flight item per report -- so concurrent submissions cannot both create work.

Revision ID: 1bfc0d20a8de
Revises:
Create Date: 2026-07-22 12:27:43.111363

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1bfc0d20a8de"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_processing_runs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("requested_by_user_id", sa.UUID(), nullable=True),
        sa.Column("caller", sa.String(length=64), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column("force_reprocess", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ai_processing_runs_created_at", "ai_processing_runs", ["created_at"], unique=False
    )
    op.create_table(
        "ai_processing_run_items",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("content_hash", sa.String(length=128), nullable=True),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'queued', 'processing', 'classifying', 'extracting', 'generating_insights', 'completed', 'failed', 'rejected', 'cancelled')",
            name="ck_ai_processing_run_items_status",
        ),
        sa.ForeignKeyConstraint(["run_id"], ["ai_processing_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ai_run_items_report_id", "ai_processing_run_items", ["report_id"], unique=False
    )
    op.create_index("ix_ai_run_items_run_id", "ai_processing_run_items", ["run_id"], unique=False)
    op.create_index("ix_ai_run_items_status", "ai_processing_run_items", ["status"], unique=False)
    op.create_index(
        "uq_ai_run_items_active_report",
        "ai_processing_run_items",
        ["report_id"],
        unique=True,
        postgresql_where=sa.text(
            "status IN ('classifying', 'extracting', 'generating_insights', 'pending', 'processing', 'queued')"
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_ai_run_items_active_report",
        table_name="ai_processing_run_items",
        postgresql_where=sa.text(
            "status IN ('classifying', 'extracting', 'generating_insights', 'pending', 'processing', 'queued')"
        ),
    )
    op.drop_index("ix_ai_run_items_status", table_name="ai_processing_run_items")
    op.drop_index("ix_ai_run_items_run_id", table_name="ai_processing_run_items")
    op.drop_index("ix_ai_run_items_report_id", table_name="ai_processing_run_items")
    op.drop_table("ai_processing_run_items")
    op.drop_index("ix_ai_processing_runs_created_at", table_name="ai_processing_runs")
    op.drop_table("ai_processing_runs")
