"""ai tables for document-based processing

Revision ID: d8aa1d302d24
Revises:
Create Date: 2026-07-23 16:29:59.111638

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d8aa1d302d24"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_processing_runs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("requested_by_user_id", sa.UUID(), nullable=True),
        sa.Column("caller", sa.String(length=64), nullable=False),
        sa.Column("request_id", sa.String(length=128), nullable=True),
        sa.Column("force_reprocess", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ai_processing_runs_created_at", "ai_processing_runs", ["created_at"], unique=False
    )
    op.create_table(
        "ai_processing_run_items",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("reports_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("content_hash", sa.String(length=128), nullable=True),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'queued', 'processing', 'classifying', 'extracting', 'generating_insights', 'completed', 'failed', 'rejected', 'cancelled')",
            name="ck_ai_processing_run_items_status",
        ),
        sa.ForeignKeyConstraint(["run_id"], ["ai_processing_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ai_run_items_document_id", "ai_processing_run_items", ["document_id"], unique=False
    )
    op.create_index("ix_ai_run_items_run_id", "ai_processing_run_items", ["run_id"], unique=False)
    op.create_index("ix_ai_run_items_status", "ai_processing_run_items", ["status"], unique=False)
    op.create_index(
        "uq_ai_run_items_active_document",
        "ai_processing_run_items",
        ["document_id"],
        unique=True,
        postgresql_where=sa.text(
            "status IN ('classifying', 'extracting', 'generating_insights', 'pending', 'processing', 'queued')"
        ),
    )
    op.create_table(
        "ai_process_logs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("run_item_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("input_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "cache_read_input_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "cache_creation_input_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "estimated_cost_usd",
            sa.Numeric(precision=12, scale=6),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("duration_ms", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_item_id"], ["ai_processing_run_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "run_item_id", "stage", "attempt", name="uq_ai_process_logs_item_stage_attempt"
        ),
    )
    op.create_table(
        "ai_report_classifications",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("run_item_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("section", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_item_id"], ["ai_processing_run_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_item_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ai_report_classifications")
    op.drop_table("ai_process_logs")
    op.drop_index(
        "uq_ai_run_items_active_document",
        table_name="ai_processing_run_items",
        postgresql_where=sa.text(
            "status IN ('classifying', 'extracting', 'generating_insights', 'pending', 'processing', 'queued')"
        ),
    )
    op.drop_index("ix_ai_run_items_status", table_name="ai_processing_run_items")
    op.drop_index("ix_ai_run_items_run_id", table_name="ai_processing_run_items")
    op.drop_index("ix_ai_run_items_document_id", table_name="ai_processing_run_items")
    op.drop_table("ai_processing_run_items")
    op.drop_index("ix_ai_processing_runs_created_at", table_name="ai_processing_runs")
    op.drop_table("ai_processing_runs")
    # ### end Alembic commands ###
