"""Ownership rules for Alembic autogenerate.

This database is shared with the Spring backend. Without this filter,
``alembic revision --autogenerate`` would see ~31 unmodelled Spring tables and emit
``DROP TABLE`` for every one of them.

It lives here rather than in ``alembic/env.py`` because it is load-bearing safety
logic that must be unit-testable — ``env.py`` can only be imported inside a live
Alembic run.
"""

from typing import Any

OWNED_PREFIX = "ai_"
VERSION_TABLE = "ai_alembic_version"


def owns_table(name: str | None) -> bool:
    """True only for tables this service owns."""
    if not name:
        return False
    return name.startswith(OWNED_PREFIX) or name == VERSION_TABLE


def include_object(
    obj: Any,
    name: str | None,
    type_: str,
    reflected: bool,
    compare_to: Any,
) -> bool:
    """Alembic ``include_object`` hook. Excludes everything not owned here."""
    if type_ == "table":
        return owns_table(name)

    # Indexes and constraints are judged by the table they belong to, so a Spring
    # table's index can never be swept into an autogenerated migration.
    parent = getattr(obj, "table", None)
    if parent is not None:
        return owns_table(getattr(parent, "name", None))

    return True
